name: fastq-dl
on:
  push:
    branches: [ main, master, dev ]
  pull_request:
    branches: [ main, master, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout rpetit3/fastq-dl
        uses: actions/checkout@v2

      - uses: taiki-e/install-action@just

      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: '3.10'
          miniforge-variant: Mambaforge
          channels: conda-forge,bioconda
          channel-priority: strict
          activate-environment: fastq-dl
          environment-file: environment.yml
          auto-update-conda: true

      - name: Install fastq-dl
        run: just install

      - name: Check formatting
        run: just check-fmt

      - name: Lint
        run: just lint

      - name: Test fastq-dl
        run: |
          fastq-dl --version
          fastq-dl --help

      - name: Test ENA Download
        run: |
          fastq-dl --accession SRX1390608 --outdir test-ena --verbose

      - name: Test SRA Download
        run: |
          fastq-dl --accession SRX1390608 --provider SRA --outdir test-sra --verbose

      - name: Test Experiment with duplicate runs
        run: |
          fastq-dl --accession ERX012546 --provider sra --outdir test-duplicate --verbose

      - name: Test Small Run (SRA)
        run: |
          fastq-dl --accession SRX3606281 --provider SrA --outdir test-small-sra --verbose

      - name: Test Small Run (ENA)
        run: |
          fastq-dl --accession SRX3606281 --outdir test-small-ena --verbose

      - name: Test BioSample (ENA)
        run: |
          fastq-dl --accession SAMN06191622 --outdir test-biosample --verbose

      - name: Test Sample (SRA)
        run: |
          fastq-dl --accession SRS1904245 --provider SRA --outdir test-sample --verbose
